Vagrant.configure('2') do |config|
  # Disable vagrant-berkshelf for projects without a Berksfile
  if Vagrant.has_plugin?('vagrant-berkshelf') && !File.exists?("./Berksfile")
    config.berkshelf.enabled = false
  end

  config.vm.provider :virtualbox do |virtualbox, override|
  end

  config.vm.provider :vmware_fusion do |vmware_fusion, override|
  end
end
